### ISSUE TITLE
Move (fork) this project to the openwichita GitHub

### ISSUE THREAD

**Issue by caketron** [caketron/lake-afton-presenter-notes#2]

**Comment by nessalc** [comment]
Should move to [Lake Afton GitHub](https://github.com/lake-afton-public-observatory).

**Comment by caketron** [comment]
Yes, Seth has just granted me access to do so. It is on my immediate to do list. Will let you know once completed. 

Thanks
Chris Ketron

**Comment by caketron** [comment]
Closing this issue as a new repo has been created in [lake-afton-public-observatory](https://github.com/lake-afton-public-observatory/lake-afton-presenter-notes)
